apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass.yaml
  - namespace.yaml
  - mongo-service.yaml
  - mongo-statefulset.yaml
  - pacman-deployment.yaml
  - pacman-service.yaml
